# Generated by Django 3.0.3 on 2020-03-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email_id', models.CharField(max_length=50)),
                ('Locality', models.TextField()),
                ('phone_no', models.IntegerField()),
                ('expert', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email_id', models.CharField(max_length=50)),
                ('Locality', models.TextField()),
                ('phone_no', models.IntegerField()),
                ('expert', models.TextField()),
            ],
        ),
    ]
