# Generated by Django 3.0.3 on 2020-04-26 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name=150)),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='colabUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='stuDents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stuDent', models.BooleanField(default=False)),
                ('articles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Articles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.colabUser')),
            ],
        ),
        migrations.CreateModel(
            name='menTors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_menTor', models.BooleanField(default=False)),
                ('articles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Articles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.colabUser')),
            ],
        ),
    ]
